// ABOUTME: Tunnel protocol v1 for the VCS Connector — one Envelope per binary WS frame.
// ABOUTME: Defines HTTPRequest/HTTPResponseHead/BodyChunk/Cancel/CancelAck/Error messages.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tunnel/tunnel.proto

package tunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeadlineClass selects the gateway/connector deadline profile for a request.
type DeadlineClass int32

const (
	DeadlineClass_DEADLINE_CLASS_UNSPECIFIED DeadlineClass = 0
	DeadlineClass_DEADLINE_CLASS_INTERACTIVE DeadlineClass = 1
	DeadlineClass_DEADLINE_CLASS_BULK        DeadlineClass = 2
)

// Enum value maps for DeadlineClass.
var (
	DeadlineClass_name = map[int32]string{
		0: "DEADLINE_CLASS_UNSPECIFIED",
		1: "DEADLINE_CLASS_INTERACTIVE",
		2: "DEADLINE_CLASS_BULK",
	}
	DeadlineClass_value = map[string]int32{
		"DEADLINE_CLASS_UNSPECIFIED": 0,
		"DEADLINE_CLASS_INTERACTIVE": 1,
		"DEADLINE_CLASS_BULK":        2,
	}
)

func (x DeadlineClass) Enum() *DeadlineClass {
	p := new(DeadlineClass)
	*p = x
	return p
}

func (x DeadlineClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeadlineClass) Descriptor() protoreflect.EnumDescriptor {
	return file_tunnel_tunnel_proto_enumTypes[0].Descriptor()
}

func (DeadlineClass) Type() protoreflect.EnumType {
	return &file_tunnel_tunnel_proto_enumTypes[0]
}

func (x DeadlineClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeadlineClass.Descriptor instead.
func (DeadlineClass) EnumDescriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{0}
}

// CancelOutcome is the true terminal state of a cancelled exchange.
type CancelOutcome int32

const (
	CancelOutcome_CANCEL_OUTCOME_UNSPECIFIED CancelOutcome = 0
	// The upstream request was never sent.
	CancelOutcome_CANCEL_OUTCOME_NOT_SENT CancelOutcome = 1
	// The upstream request completed before the cancel took effect.
	CancelOutcome_CANCEL_OUTCOME_COMPLETED CancelOutcome = 2
	// The upstream request was in flight; its effect is unknown.
	CancelOutcome_CANCEL_OUTCOME_OUTCOME_UNKNOWN CancelOutcome = 3
)

// Enum value maps for CancelOutcome.
var (
	CancelOutcome_name = map[int32]string{
		0: "CANCEL_OUTCOME_UNSPECIFIED",
		1: "CANCEL_OUTCOME_NOT_SENT",
		2: "CANCEL_OUTCOME_COMPLETED",
		3: "CANCEL_OUTCOME_OUTCOME_UNKNOWN",
	}
	CancelOutcome_value = map[string]int32{
		"CANCEL_OUTCOME_UNSPECIFIED":     0,
		"CANCEL_OUTCOME_NOT_SENT":        1,
		"CANCEL_OUTCOME_COMPLETED":       2,
		"CANCEL_OUTCOME_OUTCOME_UNKNOWN": 3,
	}
)

func (x CancelOutcome) Enum() *CancelOutcome {
	p := new(CancelOutcome)
	*p = x
	return p
}

func (x CancelOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_tunnel_tunnel_proto_enumTypes[1].Descriptor()
}

func (CancelOutcome) Type() protoreflect.EnumType {
	return &file_tunnel_tunnel_proto_enumTypes[1]
}

func (x CancelOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelOutcome.Descriptor instead.
func (CancelOutcome) EnumDescriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{1}
}

// ErrorOrigin identifies which hop produced an Error.
type ErrorOrigin int32

const (
	ErrorOrigin_ERROR_ORIGIN_UNSPECIFIED ErrorOrigin = 0
	ErrorOrigin_ERROR_ORIGIN_GATEWAY     ErrorOrigin = 1
	ErrorOrigin_ERROR_ORIGIN_CONNECTOR   ErrorOrigin = 2
	ErrorOrigin_ERROR_ORIGIN_UPSTREAM    ErrorOrigin = 3
)

// Enum value maps for ErrorOrigin.
var (
	ErrorOrigin_name = map[int32]string{
		0: "ERROR_ORIGIN_UNSPECIFIED",
		1: "ERROR_ORIGIN_GATEWAY",
		2: "ERROR_ORIGIN_CONNECTOR",
		3: "ERROR_ORIGIN_UPSTREAM",
	}
	ErrorOrigin_value = map[string]int32{
		"ERROR_ORIGIN_UNSPECIFIED": 0,
		"ERROR_ORIGIN_GATEWAY":     1,
		"ERROR_ORIGIN_CONNECTOR":   2,
		"ERROR_ORIGIN_UPSTREAM":    3,
	}
)

func (x ErrorOrigin) Enum() *ErrorOrigin {
	p := new(ErrorOrigin)
	*p = x
	return p
}

func (x ErrorOrigin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorOrigin) Descriptor() protoreflect.EnumDescriptor {
	return file_tunnel_tunnel_proto_enumTypes[2].Descriptor()
}

func (ErrorOrigin) Type() protoreflect.EnumType {
	return &file_tunnel_tunnel_proto_enumTypes[2]
}

func (x ErrorOrigin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorOrigin.Descriptor instead.
func (ErrorOrigin) EnumDescriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{2}
}

// Envelope is the single unit of transport: exactly one Envelope per binary
// WebSocket frame. All frames of one exchange carry the same request_id.
type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Envelope_HttpRequest
	//	*Envelope_HttpResponseHead
	//	*Envelope_BodyChunk
	//	*Envelope_Cancel
	//	*Envelope_CancelAck
	//	*Envelope_Error
	Msg           isEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_tunnel_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetMsg() isEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Envelope) GetHttpRequest() *HTTPRequest {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *Envelope) GetHttpResponseHead() *HTTPResponseHead {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_HttpResponseHead); ok {
			return x.HttpResponseHead
		}
	}
	return nil
}

func (x *Envelope) GetBodyChunk() *BodyChunk {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_BodyChunk); ok {
			return x.BodyChunk
		}
	}
	return nil
}

func (x *Envelope) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *Envelope) GetCancelAck() *CancelAck {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_CancelAck); ok {
			return x.CancelAck
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Msg interface {
	isEnvelope_Msg()
}

type Envelope_HttpRequest struct {
	HttpRequest *HTTPRequest `protobuf:"bytes,2,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type Envelope_HttpResponseHead struct {
	HttpResponseHead *HTTPResponseHead `protobuf:"bytes,3,opt,name=http_response_head,json=httpResponseHead,proto3,oneof"`
}

type Envelope_BodyChunk struct {
	BodyChunk *BodyChunk `protobuf:"bytes,4,opt,name=body_chunk,json=bodyChunk,proto3,oneof"`
}

type Envelope_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,5,opt,name=cancel,proto3,oneof"`
}

type Envelope_CancelAck struct {
	CancelAck *CancelAck `protobuf:"bytes,6,opt,name=cancel_ack,json=cancelAck,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

func (*Envelope_HttpRequest) isEnvelope_Msg() {}

func (*Envelope_HttpResponseHead) isEnvelope_Msg() {}

func (*Envelope_BodyChunk) isEnvelope_Msg() {}

func (*Envelope_Cancel) isEnvelope_Msg() {}

func (*Envelope_CancelAck) isEnvelope_Msg() {}

func (*Envelope_Error) isEnvelope_Msg() {}

// HeaderValues holds the ordered values of one HTTP header.
type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_tunnel_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// HTTPRequest carries path only (no scheme/host); the connector prepends its
// configured endpoint. Headers must already be allowlisted by the sender.
type HTTPRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Method        string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeadlineClass DeadlineClass            `protobuf:"varint,5,opt,name=deadline_class,json=deadlineClass,proto3,enum=zenfra.tunnel.v1.DeadlineClass" json:"deadline_class,omitempty"`
	// When true the request body follows as BodyChunk frames.
	HasBody       bool `protobuf:"varint,6,opt,name=has_body,json=hasBody,proto3" json:"has_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	mi := &file_tunnel_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HTTPRequest) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPRequest) GetDeadlineClass() DeadlineClass {
	if x != nil {
		return x.DeadlineClass
	}
	return DeadlineClass_DEADLINE_CLASS_UNSPECIFIED
}

func (x *HTTPRequest) GetHasBody() bool {
	if x != nil {
		return x.HasBody
	}
	return false
}

// HTTPResponseHead precedes the response body chunks.
type HTTPResponseHead struct {
	state   protoimpl.MessageState   `protogen:"open.v1"`
	Status  int32                    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers map[string]*HeaderValues `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// When true the response body follows as BodyChunk frames.
	HasBody       bool `protobuf:"varint,3,opt,name=has_body,json=hasBody,proto3" json:"has_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponseHead) Reset() {
	*x = HTTPResponseHead{}
	mi := &file_tunnel_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponseHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponseHead) ProtoMessage() {}

func (x *HTTPResponseHead) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponseHead.ProtoReflect.Descriptor instead.
func (*HTTPResponseHead) Descriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *HTTPResponseHead) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HTTPResponseHead) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPResponseHead) GetHasBody() bool {
	if x != nil {
		return x.HasBody
	}
	return false
}

// BodyChunk streams a request or response body. Sequence starts at 0 and
// increments by 1; data is capped at 64 KiB; terminal marks the last chunk.
type BodyChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Terminal      bool                   `protobuf:"varint,3,opt,name=terminal,proto3" json:"terminal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyChunk) Reset() {
	*x = BodyChunk{}
	mi := &file_tunnel_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyChunk) ProtoMessage() {}

func (x *BodyChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyChunk.ProtoReflect.Descriptor instead.
func (*BodyChunk) Descriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *BodyChunk) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *BodyChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BodyChunk) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

// Cancel asks the peer to abort the exchange identified by request_id.
type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_tunnel_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{5}
}

// CancelAck answers a Cancel with the exchange's terminal state.
type CancelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       CancelOutcome          `protobuf:"varint,1,opt,name=outcome,proto3,enum=zenfra.tunnel.v1.CancelOutcome" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAck) Reset() {
	*x = CancelAck{}
	mi := &file_tunnel_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAck) ProtoMessage() {}

func (x *CancelAck) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAck.ProtoReflect.Descriptor instead.
func (*CancelAck) Descriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *CancelAck) GetOutcome() CancelOutcome {
	if x != nil {
		return x.Outcome
	}
	return CancelOutcome_CANCEL_OUTCOME_UNSPECIFIED
}

// Error terminates an exchange with a stable machine-readable code (see the
// ErrCode* constants in this package), an explicit retryability signal, and
// the originating hop.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Origin        ErrorOrigin            `protobuf:"varint,4,opt,name=origin,proto3,enum=zenfra.tunnel.v1.ErrorOrigin" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_tunnel_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_tunnel_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Error) GetOrigin() ErrorOrigin {
	if x != nil {
		return x.Origin
	}
	return ErrorOrigin_ERROR_ORIGIN_UNSPECIFIED
}

var File_tunnel_tunnel_proto protoreflect.FileDescriptor

const file_tunnel_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x13tunnel/tunnel.proto\x12\x10zenfra.tunnel.v1\"\xa9\x03\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12B\n" +
	"\fhttp_request\x18\x02 \x01(\v2\x1d.zenfra.tunnel.v1.HTTPRequestH\x00R\vhttpRequest\x12R\n" +
	"\x12http_response_head\x18\x03 \x01(\v2\".zenfra.tunnel.v1.HTTPResponseHeadH\x00R\x10httpResponseHead\x12<\n" +
	"\n" +
	"body_chunk\x18\x04 \x01(\v2\x1b.zenfra.tunnel.v1.BodyChunkH\x00R\tbodyChunk\x122\n" +
	"\x06cancel\x18\x05 \x01(\v2\x18.zenfra.tunnel.v1.CancelH\x00R\x06cancel\x12<\n" +
	"\n" +
	"cancel_ack\x18\x06 \x01(\v2\x1b.zenfra.tunnel.v1.CancelAckH\x00R\tcancelAck\x12/\n" +
	"\x05error\x18\a \x01(\v2\x17.zenfra.tunnel.v1.ErrorH\x00R\x05errorB\x05\n" +
	"\x03msg\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xd4\x02\n" +
	"\vHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12D\n" +
	"\aheaders\x18\x04 \x03(\v2*.zenfra.tunnel.v1.HTTPRequest.HeadersEntryR\aheaders\x12F\n" +
	"\x0edeadline_class\x18\x05 \x01(\x0e2\x1f.zenfra.tunnel.v1.DeadlineClassR\rdeadlineClass\x12\x19\n" +
	"\bhas_body\x18\x06 \x01(\bR\ahasBody\x1aZ\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.zenfra.tunnel.v1.HeaderValuesR\x05value:\x028\x01\"\xec\x01\n" +
	"\x10HTTPResponseHead\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12I\n" +
	"\aheaders\x18\x02 \x03(\v2/.zenfra.tunnel.v1.HTTPResponseHead.HeadersEntryR\aheaders\x12\x19\n" +
	"\bhas_body\x18\x03 \x01(\bR\ahasBody\x1aZ\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.zenfra.tunnel.v1.HeaderValuesR\x05value:\x028\x01\"W\n" +
	"\tBodyChunk\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bterminal\x18\x03 \x01(\bR\bterminal\"\b\n" +
	"\x06Cancel\"F\n" +
	"\tCancelAck\x129\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x1f.zenfra.tunnel.v1.CancelOutcomeR\aoutcome\"\x8a\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x125\n" +
	"\x06origin\x18\x04 \x01(\x0e2\x1d.zenfra.tunnel.v1.ErrorOriginR\x06origin*h\n" +
	"\rDeadlineClass\x12\x1e\n" +
	"\x1aDEADLINE_CLASS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDEADLINE_CLASS_INTERACTIVE\x10\x01\x12\x17\n" +
	"\x13DEADLINE_CLASS_BULK\x10\x02*\x8e\x01\n" +
	"\rCancelOutcome\x12\x1e\n" +
	"\x1aCANCEL_OUTCOME_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CANCEL_OUTCOME_NOT_SENT\x10\x01\x12\x1c\n" +
	"\x18CANCEL_OUTCOME_COMPLETED\x10\x02\x12\"\n" +
	"\x1eCANCEL_OUTCOME_OUTCOME_UNKNOWN\x10\x03*|\n" +
	"\vErrorOrigin\x12\x1c\n" +
	"\x18ERROR_ORIGIN_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ERROR_ORIGIN_GATEWAY\x10\x01\x12\x1a\n" +
	"\x16ERROR_ORIGIN_CONNECTOR\x10\x02\x12\x19\n" +
	"\x15ERROR_ORIGIN_UPSTREAM\x10\x03B4Z2github.com/ZenfraCloud/zenfra-vcs-connector/tunnelb\x06proto3"

var (
	file_tunnel_tunnel_proto_rawDescOnce sync.Once
	file_tunnel_tunnel_proto_rawDescData []byte
)

func file_tunnel_tunnel_proto_rawDescGZIP() []byte {
	file_tunnel_tunnel_proto_rawDescOnce.Do(func() {
		file_tunnel_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tunnel_tunnel_proto_rawDesc), len(file_tunnel_tunnel_proto_rawDesc)))
	})
	return file_tunnel_tunnel_proto_rawDescData
}

var file_tunnel_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tunnel_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tunnel_tunnel_proto_goTypes = []any{
	(DeadlineClass)(0),       // 0: zenfra.tunnel.v1.DeadlineClass
	(CancelOutcome)(0),       // 1: zenfra.tunnel.v1.CancelOutcome
	(ErrorOrigin)(0),         // 2: zenfra.tunnel.v1.ErrorOrigin
	(*Envelope)(nil),         // 3: zenfra.tunnel.v1.Envelope
	(*HeaderValues)(nil),     // 4: zenfra.tunnel.v1.HeaderValues
	(*HTTPRequest)(nil),      // 5: zenfra.tunnel.v1.HTTPRequest
	(*HTTPResponseHead)(nil), // 6: zenfra.tunnel.v1.HTTPResponseHead
	(*BodyChunk)(nil),        // 7: zenfra.tunnel.v1.BodyChunk
	(*Cancel)(nil),           // 8: zenfra.tunnel.v1.Cancel
	(*CancelAck)(nil),        // 9: zenfra.tunnel.v1.CancelAck
	(*Error)(nil),            // 10: zenfra.tunnel.v1.Error
	nil,                      // 11: zenfra.tunnel.v1.HTTPRequest.HeadersEntry
	nil,                      // 12: zenfra.tunnel.v1.HTTPResponseHead.HeadersEntry
}
var file_tunnel_tunnel_proto_depIdxs = []int32{
	5,  // 0: zenfra.tunnel.v1.Envelope.http_request:type_name -> zenfra.tunnel.v1.HTTPRequest
	6,  // 1: zenfra.tunnel.v1.Envelope.http_response_head:type_name -> zenfra.tunnel.v1.HTTPResponseHead
	7,  // 2: zenfra.tunnel.v1.Envelope.body_chunk:type_name -> zenfra.tunnel.v1.BodyChunk
	8,  // 3: zenfra.tunnel.v1.Envelope.cancel:type_name -> zenfra.tunnel.v1.Cancel
	9,  // 4: zenfra.tunnel.v1.Envelope.cancel_ack:type_name -> zenfra.tunnel.v1.CancelAck
	10, // 5: zenfra.tunnel.v1.Envelope.error:type_name -> zenfra.tunnel.v1.Error
	11, // 6: zenfra.tunnel.v1.HTTPRequest.headers:type_name -> zenfra.tunnel.v1.HTTPRequest.HeadersEntry
	0,  // 7: zenfra.tunnel.v1.HTTPRequest.deadline_class:type_name -> zenfra.tunnel.v1.DeadlineClass
	12, // 8: zenfra.tunnel.v1.HTTPResponseHead.headers:type_name -> zenfra.tunnel.v1.HTTPResponseHead.HeadersEntry
	1,  // 9: zenfra.tunnel.v1.CancelAck.outcome:type_name -> zenfra.tunnel.v1.CancelOutcome
	2,  // 10: zenfra.tunnel.v1.Error.origin:type_name -> zenfra.tunnel.v1.ErrorOrigin
	4,  // 11: zenfra.tunnel.v1.HTTPRequest.HeadersEntry.value:type_name -> zenfra.tunnel.v1.HeaderValues
	4,  // 12: zenfra.tunnel.v1.HTTPResponseHead.HeadersEntry.value:type_name -> zenfra.tunnel.v1.HeaderValues
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_tunnel_tunnel_proto_init() }
func file_tunnel_tunnel_proto_init() {
	if File_tunnel_tunnel_proto != nil {
		return
	}
	file_tunnel_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_HttpRequest)(nil),
		(*Envelope_HttpResponseHead)(nil),
		(*Envelope_BodyChunk)(nil),
		(*Envelope_Cancel)(nil),
		(*Envelope_CancelAck)(nil),
		(*Envelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tunnel_tunnel_proto_rawDesc), len(file_tunnel_tunnel_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tunnel_tunnel_proto_goTypes,
		DependencyIndexes: file_tunnel_tunnel_proto_depIdxs,
		EnumInfos:         file_tunnel_tunnel_proto_enumTypes,
		MessageInfos:      file_tunnel_tunnel_proto_msgTypes,
	}.Build()
	File_tunnel_tunnel_proto = out.File
	file_tunnel_tunnel_proto_goTypes = nil
	file_tunnel_tunnel_proto_depIdxs = nil
}
